### ISSUE TITLE
Weird rendering of placeables listing in the preferences window

### ISSUE THREAD

**Issue by julen** [translate/virtaal#1067]
When I first open the preferences window and go to the placeables tab, all is displayed fine.

If I close the preferences window and open it again on the placeables tab, an ugly horizontal scrollbar appears on the listing. If I select an element in the listing, the long line is wrapped weirdly.

Attaching screenshots now.

**Comment by friedelwolff** [comment]
I think this is reasonably fixed now in dfbb5db. Sorry that it took more than 6 years!
