### ISSUE TITLE
plugin

### ISSUE THREAD

**Issue by transl8bzimport** [translate/virtaal#3203]
_Version: 0.7.1_

_Originally posted by (unknown user):_

I can't open any files. I get the following message : see the logfile virtaal.exe.log for details
and in virtall.exe.log : 
ERROR:root:Failed to load plugin "localtm"
(10050, 'Network is down')
Traceback (most recent call last):
  File "virtaal\controllers\plugincontroller.pyo", line 109, in enable_plugin
  File "C:\Program Files\Virtaal\virtaal_plugins\tm\models\localtm.py", line 53, in **init**
  File "C:\Program Files\Virtaal\virtaal_plugins\tm\models\localtm.py", line 107, in test_port
  File "socket.pyo", line 159, in **init**
error: (10050, 'Network is down')
Traceback (most recent call last):
  File "virtaal", line 23, in <module>
  File "virtaal\common__init__.pyo", line 21, in <module>
  File "virtaal\common\pan_app.pyo", line 226, in <module>
  File "virtaal\common\pan_app.pyo", line 166, in **init**
  File "virtaal\common\pan_app.pyo", line 170, in read
  File "ConfigParser.pyo", line 267, in read
  File "ConfigParser.pyo", line 462, in _read
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: C:\Users\flo\AppData\Roaming\Virtaal\virtaal.ini, line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

**Comment by rffontenelle** [comment]
User did not reply, unable to contact the original poster after the Bugzilla->GitHub migration. Closing.
