### ISSUE TITLE
Display of spelling errors

### ISSUE THREAD

**Issue by Sadi58** [translate/virtaal#3208]
At the moment Virtaal only shows spelling errors in the active/open segment, but I think it would be much more helpful if users could choose showing all spelling errors in the entire TMX file.

**Comment by rffontenelle** [comment]
I seems to me that Virtaal's design is made for the translator to focus on one string a time (as it opens a edit area for the selected string), but also allowing to peek other strings around the selected one.  Personally, I feel like spell checking other strings would be a unnecessary processing taking this design in consideration. I recommend using a post-translation to do a complete spellcheck -- I use [transspell](https://gitlab.com/fsfhu/fsfhu-scripts/blob/master/spellcheck/transspell).

Considering 5 years without a reply of a developer, I assume it won't be implemented. So I'm closing this. Feel free to open or add any other comment.
