### ISSUE TITLE
Location of spelling dictionaries / Turkish

### ISSUE THREAD

**Issue by Sadi58** [translate/virtaal#3209]
I wonder where the spelling dictionaries used by Virtaal are...
For I would like see if I can do something about the Turkish dictionary, which is so poor, buggy, inadequate, etc.

**Comment by rffontenelle** [comment]
@Sadi58 Virtaal uses enchant as a wrapper to use other dictionaries, like hunspell, aspell, etc. To find which dictionary you are using, I recommend running `strace -o file.txt virtaal`, open a po file in your language, close virtaal, and then search "file.txt" for `tr.dic` (or something like that for your language code).
