### ISSUE TITLE
terminology URL 404

### ISSUE THREAD

**Issue by edwintorok** [translate/virtaal#3216]
http://terminology.locamotion.org/l10n/en/hu gives me 404, and no terminology.po is downloaded
amagama got a redirect to a different site, should there be a redirect for the terminology server too,
or is there some other place I could download it?

**Comment by rffontenelle** [comment]
terminology.locamotion.org is down for some time and, after 5 years without a single reply, I assume no one has its database.  I even searched the web a bit, but not found, not even in [Wayback Machine](https://web.archive.org/).

terminology.locamotion.org support still has to be removed from Virtaal, but that's another issue.

Closing as nothing can be done.
