### ISSUE TITLE
source text modified by virtaal: spaces deleted

### ISSUE THREAD

**Issue by kwenzig** [translate/virtaal#3221]
If one opens and saves a XLIFF-File (see below), multiple spaces in the source-text are reduced to a single space. I would not expect a translation software to change the source text in any way.

```xml
<?xml version='1.0' encoding='utf-8'?>
<xliff version="1.0">
<file datatype="plaintext" original="MultiLingualeContent.fla" source-language="de" target-language="en">
<body>
<trans-unit approved="yes">
<source>A  B</source>
<target></target>
</trans-unit>
</body>
</file>
</xliff>
```

**Comment by friedelwolff** [comment]
As far as I remember, the interpretation of spacing in XLIFF is defined to be as you describe, except if xml:space="preserve" is defined. It is not ideal that we make any change to the XLIFF, though. It would be best if we can leave it untouched if we didn't have to change anything there.

I'm going to close this, as we will have to refine this more closely and report it at the Translate Toolkit where all the reading and writing of XLIFF is handled. Thank you for reporting this.

**Comment by kwenzig** [comment]
Thx for the pointer to `xml:space`. It seems that VIrtaal respects `xml:space` in `<trans-unit>` but not in `<file>`. Form my point of view Virtaal's default should be `"preserve"`. #3210 can be solved with this information.
