### ISSUE TITLE
Suggest changing "Control" to "Ctrl"

### ISSUE THREAD

**Issue by scootergrisen** [translate/virtaal#3238]
In the following string is says "Control+1".
I suggest changing it to "Ctrl+1" so its the same key name as in the other strings.

		"If you translated the previous message you should see a window with that "
		"translation and a percentage indicating how similar the source strings "
		"(English) are. It is Virtaal's translation memory at work. Press Control+1 "
		"to copy the suggested translation to the current translation. Remember to "
		"always review suggestions before you use them."

**Comment by friedelwolff** [comment]
I agree. That was the wording in the tutorial in previous versions. @unho,
will you be able to look at this? Thanks!

**Comment by unho** [comment]
Yes, I fix this on the weekend.
