### ISSUE TITLE
Does it work on OSX?

### ISSUE THREAD

**Issue by jazzybeat** [translate/virtaal#3241]
App crashes just after opening on OSX.
![usernotificationcenter](https://cloud.githubusercontent.com/assets/815706/14031673/46b844cc-f1e4-11e5-82ce-7c97d35361d5.png)

**Comment by cimm** [comment]
Same for me on El Capitan. Given it's a `beta` that hasn't moved since 2012 I seriously doubt if this will ever work.

**Comment by kwenzig** [comment]
Ich kehre zurück am 02.05.2016.

Dann werde ich mich um das Anliegen kümmern.
Beste Grüße
Knut Wenzig


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[translate/virtaal] Does it work on OSX? (#3241)" gesendet am 04/26/2016
20:46:05.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by julen** [comment]
@cimm as highlighted in the last status update by @friedelwolff, help is pretty much needed: http://markmail.org/thread/loqqqhaekpmf47hr
If you have the time and will, the aid to make it happen will be highly appreciated!

**Comment by kwenzig** [comment]
Ich kehre zurück am 02.05.2016.

Dann werde ich mich um das Anliegen kümmern.
Beste Grüße
Knut Wenzig


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[translate/virtaal] Does it work on OSX? (#3241)" gesendet am 04/26/2016
23:34:34.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by albertoDOM** [comment]
Hello.
I know help is needed to improve de OSX version so I don't want to cause annoyance. Only want to know if there is any new about this issue.

Thanks in advance.

**Comment by friedelwolff** [comment]
@dwaynebailey was doing some work before on packaging for OSX, but the currently released versions don't work at all, and I think there is a bit of work required. It will need time from somebody who can make it work. I don't have access to such a platform.

**Comment by albertoDOM** [comment]
Hi @friedelwolff.
Thanks for your information.
Hope somebody can help.

**Comment by skybridgetranslation** [comment]
I'm trying it out on VMware Mint rather than macOS.   If it doesn't work I'm back to working with trusty OmegaT.
