### ISSUE TITLE
Validation error when using some non-english characters

### ISSUE THREAD

**Issue by scootergrisen** [translate/virtaal#3248]
I suggest adding valid accelerator characters depending on the destination language.

So i my language (danish) i get validation error if i translate:

    "_Open"

To:

    "_Åbn"

In my language we have æøåÆØÅéÉ so i guess those characters should be valid. At least then translating to danish.

**Comment by friedelwolff** [comment]
Thank you for reporting this. Virtaal uses this check form the Translate Toolkit (and the same is also used in Pootle and maybe other tools). If those characters are always acceptable (all users use the Danish layout), then maybe you can report it as an enhancement for the Translate Toolkit, and future versions of Pootle and Virtaal should automatically have the updated behaviour. There is already infrastructure for such exceptions.
