### ISSUE TITLE
XLIFF 2.0 support

### ISSUE THREAD

**Issue by millin** [translate/virtaal#3264]
Do you have a plan to do it?

**Comment by friedelwolff** [comment]
Virtaal doesn't implement much internally in terms of file support. It mostly just uses what is available in the [Translate Toolkit](https://github.com/translate/translate/). I haven't had time to look much into XLIFF 2.0, but I guess the existing support in the Translate Toolkit should provide a reasonably start for a programmer who wants to add support.

**Comment by rffontenelle** [comment]
Work in progress in translate-toolkit: translate/translate#3369. Closing as it seems that nothing t be done in Virtaal.
