### ISSUE TITLE
Virtaal docs missing from website

### ISSUE THREAD

**Issue by llimeht** [translate/virtaal#3277]
The Virtaal documentation is supposed to be at http://docs.translatehouse.org/projects/virtaal/en/latest/ however this location is currently 404.

The absence of this sphinx-generated documentation is currently causing translate-toolkit's CI to fail as it pulls the inter-sphinx mapping as part of the build. Obviously the best thing is for the documentation to come back, but should translate-toolkit stop looking for virtaal's documentation in the interim?

```
SphinxWarning: intersphinx inventory 'http://docs.translatehouse.org/projects/virtaal/en/latest/objects.inv'
not fetchable due to <class 'requests.exceptions.HTTPError'>: 
404 Client Error: Not Found for url: http://docs.translatehouse.org/projects/virtaal/en/latest/objects.inv
```

**Comment by nijel** [comment]
It looks like Virtall project has been removed from readthedocs... Not sure if that was intentional or not however it was quite unpleasant as thanks to intershinx it breaks docs for other projects. So I've registered it back: https://readthedocs.org/projects/virtaal/

I've added @unho as maintainer as that was first of involved people who seems to have account on readthedocs, feel free to let me know if somebody else should be in charge here.

**Comment by unho** [comment]
The docs for Virtaal are in http://virtaal.readthedocs.io/en/latest/

I have logged in to ReadTheDocs and some warning is shown about webhooks not configured, but I don't see what is wrong. I am removing the only link in TTK docs to Virtaal docs to keep TTK builds passing.

**Comment by rffontenelle** [comment]
Virtaal docs seems to be up and running. Should this issue be closed?

**Comment by nijel** [comment]
The webhook is still missing, so the documentation is not updated on new commits.

**Comment by rffontenelle** [comment]
So what is needed is a member to apply these instructions: https://docs.readthedocs.io/en/stable/webhooks.html#github ?

**Comment by nijel** [comment]
Yes, can be done here: https://readthedocs.org/dashboard/virtaal/integrations/

**Comment by rffontenelle** [comment]
Hmm, the [integrations](https://readthedocs.org/dashboard/virtaal/integrations/) page gives me "This page does not exist yet". I can reach [dashboard](https://readthedocs.org/dashboard/virtaal/) page, though. Maybe only maintainers can see it.

**Comment by nijel** [comment]
Yes, you have to be admin on rtd.org

**Comment by friedelwolff** [comment]
I'm unfamiliar with read the docs and what is required. Can we make @rffontenelle an admin there, or what is required?

**Comment by nijel** [comment]
You need to be admin on both sides (readthedos and github) to install the integration.

Anyway I tried that and got: `User rffontenelle does not exist`

**Comment by friedelwolff** [comment]
Ok, I made him an admin temporarily for Virtaal. I hope that helps. I don't think I have any permissions at readthedocs.

**Comment by rffontenelle** [comment]
> You need to be admin on both sides (readthedos and github) to install the integration.
> 
> Anyway I tried that and got: `User rffontenelle does not exist`

My user in readthedos would be `rafaelff`.

**Comment by nijel** [comment]
@rffontenelle I've just added you.

**Comment by rffontenelle** [comment]
> Ok, I made him an admin temporarily for Virtaal. I hope that helps. I don't think I have any permissions at readthedocs.

Unfortunately, it seems the "Collaborator" in GitHub can't see any item under _Settings > Options_, but I would need _Webhooks_ in there (I can see it in my fork).

**Comment by rffontenelle** [comment]
@nijel rtd.org looks good, děkuji

**Comment by friedelwolff** [comment]
@rffontenelle Mmm, what should I do instead of "collaborator"?

**Comment by rffontenelle** [comment]
@friedelwolff The way I see, we have 3 options:
1. assign me temporarily with "member" role to have more "more granular access permissions" (quoting [1](https://help.github.com/en/github/getting-started-with-github/access-permissions-on-github)) so I can do it 
2. do this in GitHub yourself infollowing the (webhooks instructions on rtd](https://docs.readthedocs.io/en/stable/webhooks.html#github), and let me know so I resync on rtd.org's side.
3. same as 2, but you having maintainer role in rtd.org so you can do it on both ends.

**Comment by rffontenelle** [comment]
@friedelwolff Bummer. It seems I was wrong and "member" role doesn't have access to the "Options" items. My guess now is that only "owner" can do it.

**Comment by friedelwolff** [comment]
Thank you, @rffontenelle. I'm closing since the reported issue is fixed. I think let's rather think about building for release branches rather than feature branches. So the next version will necessitate a version for 0.7, for example. Say if you think this is incorrect.

**Comment by rffontenelle** [comment]
@friedelwolff My idea was to have a "development" view of the documentation, but releases branch is a better indeed.
