### ISSUE TITLE
virtaal 0.7.1 adds a semicolon to the plural formula

### ISSUE THREAD

**Issue by dasj19** [translate/virtaal#3282]
Hi, I have noticed that when translating english to romanian virtaal silently modifies the plural formula adding an uneeded semicolon at the end.

Example:
Virtaal saves the file with the following formula:
"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : (n==0 || (n%100 > 0 && n%100 < "
"20)) ? 1 : 2);;\n"

The correct plural form header wold be (without semicolon at the end):
"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : (n==0 || (n%100 > 0 && n%100 < "
"20)) ? 1 : 2);\n"

**Comment by rffontenelle** [comment]
@dasj19 Which version were you using when this happened (0.7.1, 1.0.0 beta 1, other)? Does this still happen?

**Comment by dasj19** [comment]
0.7.1 had the issue... I just tested with 1.0.0-beta1 and the issue was not present

**Comment by rffontenelle** [comment]
Since it is already fixed in newer (unreleased) version, I guess there isn't much we can do. But thanks for reporting it!
