### ISSUE TITLE
Open a "pot" file but title/properties says "po"

### ISSUE THREAD

**Issue by scootergrisen** [translate/virtaal#3294]
Virtaal does not show correct file name when a pot file is opened.

When i open a file ending with ".pot" like "virtaal.pot" it says "virtaal.po" in the title ("t" is missing).

This is not good because there might be a file called "virtaal.po".
Suppose you have both these files in the same folder:

    "virtaal.pot"
    "virtaal.po"

Open the "virtaal.pot" file and how can you know what file is open in Virtaal?
Title is wrong and also properties dialog (Alt+Enter) says the wrong location "...virtaal.po".

**Comment by friedelwolff** [comment]
This is on purpose. The .pot file is handled as a template from where the "real" translation file is created. This is the same behaviour when opening templates in for example LibreOffice. In many cases when you open virtaal.pot you want to create da.po (or similar) afterwards.

I don't see the case of .pot and .po next to each other happening often, but reopen if you feel I'm missing an important case.
