### ISSUE TITLE
AutoHotKey scripts don't work in Virtaal 

### ISSUE THREAD

**Issue by msoutopico** [translate/virtaal#3302]
I use an AutoHotKey script([1]) to insert a non-breaking space (and other characters) in my translations, but it doesn't seem to work in Virtaal (when I press Ctrl+Shift+space nothing happens). 

[1]: https://gist.github.com/msoutopico/fcc15c7db5ba211dce66fa73723d7d62

**Comment by friedelwolff** [comment]
I'm not familiar with AutoHotKey, but I guess it is a tool for Windows?

As I understand it, Gtk intercepts the keyboard events at a low level on Windows, and doesn't integrate with the Windows key presses as other applications do. I think that is what is causing the issue you are seeing.

As a workaround, you can use the Gtk method to insert arbitrary Unicode characters: Ctrl+Shift+U and then "AD" (while the 'u' character is underlined). I hope that works.

There is nothing at this stage that we can do about this as far as I know.

**Comment by msoutopico** [comment]
Hi Friedel,

Thanks for your answer.

Yes, AutoHotKey only runs on WIndows as far as I know.

Thanks for your workaround, but I'm not sure I understand what "AD" means.
I can press Ctrl+Shft+U. when indeed shows an underlined 'u', and then I
understand that I must type the hex code of the character, in this case,
"A0" (as the two leading zeros in 00A0 seem to be unnecessary). I guess
that's what you meant, and it seems to work. Thanks!

Cheers, Manuel

**Comment by friedelwolff** [comment]
Ah, yes, I had the code wrong. I meant A0, of course.
