### ISSUE TITLE
Documentation is gone

### ISSUE THREAD

**Issue by nijel** [translate/virtaal#3319]
https://virtaal.readthedocs.io/en/latest/ redirects to https://docs.translatehouse.org/projects/virtaal/en/latest/ which does not exist.

I think it was working yesterday.

**Comment by nijel** [comment]
See also https://github.com/translate/virtaal/issues/3277

**Comment by nijel** [comment]
I think the problem is that virtaal is not a subproject of https://readthedocs.org/projects/translate/, I don't have access to change that...

**Comment by rffontenelle** [comment]
@nijel Thanks for spotting this issue, and sorry for causing this problem. I tried setting the "Domain" option on Virtaal readthedocs, which didn't seem to work, but I didn't expected to pop up errors like that. Reverted and now https://virtaal.readthedocs.io/en/latest/ is back.

By the way, you have access to Virtaal project on readthedocs: https://readthedocs.org/projects/virtaal/

Do you have any clue on how to put Virtaal documentation under https://docs.translatehouse.org/projects?

**Comment by rffontenelle** [comment]
> I think the problem is that virtaal is not a subproject of https://readthedocs.org/projects/translate/, I don't have access to change that...

That's was it. Now I received access to /translate/, so I added virtaal as subproject. Documentation is not available at https://docs.translatehouse.org/projects/virtaal/en/latest/. Let me know if you find any other problems.
